# Generated by Django 6.0.4 on 2026-06-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='completed_jobs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='List of mechanic skills'),
        ),
    ]
