# Generated by Django 6.0.4 on 2026-06-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0002_mechanicprofile_completed_jobs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='garage_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='workshop_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
