# Generated by Django 6.0.4 on 2026-06-27 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_category', models.CharField(choices=[('FLAT_TYRE', 'Flat Tyre'), ('BATTERY_ISSUE', 'Battery Issue'), ('ENGINE_PROBLEM', 'Engine Problem'), ('FUEL_DELIVERY', 'Fuel Delivery'), ('ACCIDENT', 'Accident'), ('LOCKOUT', 'Lockout'), ('TOWING', 'Towing'), ('GENERAL', 'General Breakdown')], default='GENERAL', max_length=50)),
                ('problem_description', models.TextField()),
                ('emergency_contact', models.CharField(max_length=20)),
                ('current_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('current_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('ACCEPTED', 'Accepted'), ('ON_THE_WAY', 'Mechanic On The Way'), ('ARRIVED', 'Arrived'), ('REPAIR_STARTED', 'Repair Started'), ('REPAIR_COMPLETED', 'Repair Completed'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL)),
                ('preferred_mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_jobs', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_images/')),
                ('image_type', models.CharField(choices=[('PROBLEM', 'Problem Image'), ('REPAIR_BEFORE', 'Before Repair'), ('REPAIR_AFTER', 'After Repair')], default='PROBLEM', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='assistance.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='RepairDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_notes', models.TextField(blank=True, null=True)),
                ('parts_used', models.TextField(blank=True, null=True)),
                ('labour_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('parts_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repair_details', to='assistance.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('ACCEPTED', 'Accepted'), ('ON_THE_WAY', 'Mechanic On The Way'), ('ARRIVED', 'Arrived'), ('REPAIR_STARTED', 'Repair Started'), ('REPAIR_COMPLETED', 'Repair Completed'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='assistance.servicerequest')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
